// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootei
List bootei(SEXP x, SEXP y, std::string test, int B, int R, std::string alternative, double perm_seed, bool midp, std::string boot_type, bool keep_perm_stats);
RcppExport SEXP _bootei_bootei(SEXP xSEXP, SEXP ySEXP, SEXP testSEXP, SEXP BSEXP, SEXP RSEXP, SEXP alternativeSEXP, SEXP perm_seedSEXP, SEXP midpSEXP, SEXP boot_typeSEXP, SEXP keep_perm_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    Rcpp::traits::input_parameter< double >::type perm_seed(perm_seedSEXP);
    Rcpp::traits::input_parameter< bool >::type midp(midpSEXP);
    Rcpp::traits::input_parameter< std::string >::type boot_type(boot_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_perm_stats(keep_perm_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(bootei(x, y, test, B, R, alternative, perm_seed, midp, boot_type, keep_perm_stats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bootei_bootei", (DL_FUNC) &_bootei_bootei, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_bootei(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
