# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootei_cpp <- function(x, y, test = "chisq", B = 100L, R = 1000L, alternative = "two.sided", perm_seed = NA_real_, midp = FALSE, boot_type = "sobol", keep_perm_stats = FALSE) {
    .Call(`_bootei_bootei_cpp`, x, y, test, B, R, alternative, perm_seed, midp, boot_type, keep_perm_stats)
}

